import type { MutableRefObject } from 'react';
import { createRoot } from 'react-dom/client';
import type { Root } from 'react-dom/client';
import type { GridApi } from '@opencorestack/opengridx';
import BenchGrid from './BenchGrid';
import { generateRows, REGIONS } from './data';
import type { BenchRow } from './data';
import type { BenchApi, LongTaskStats, OpResult, ReachResult, ScrollResult } from './types';

/*
 * How the timings are taken
 * -------------------------
 * Every timed operation measures "time to result on screen", not JavaScript time:
 *
 *   t0 = performance.now(), then the operation (root.render / an apiRef call) is started.
 *   We then wait on requestAnimationFrame until the DOM shows the result (a `ready()` check on the
 *   grid's DOM: rows present, aria-sort set, aria-rowcount changed, group rows with sums...).
 *   React commits inside a task; the first rAF callback that sees the committed DOM runs in the
 *   frame that paints it. One more rAF fires once that frame has been painted ("double rAF after the
 *   commit"), and performance.now() there is t1. If the commit is already visible when the
 *   operation returns, both rAFs are still awaited.
 *
 *   The result is t1 - t0. It includes React's render and commit, style, layout and paint of the
 *   first frame with the result, and at most one frame interval of waiting for vsync.
 *
 * Row data is generated by `generate()` before any timer starts and is never part of a timing.
 * The page is cross-origin isolated (COOP/COEP headers in vite.config.ts), which gives Firefox and
 * WebKit fine-grained performance.now() values instead of ones rounded to 1 ms.
 */

const OP_TIMEOUT_MS = 180_000;

let root: Root | null = null;
let rows: BenchRow[] = [];
let rowHeight = 52;
let apiRef: MutableRefObject<GridApi<BenchRow>> | null = null;

const nextFrame = () => new Promise<number>((resolve) => requestAnimationFrame(resolve));
const sleep = (ms: number) => new Promise<void>((resolve) => setTimeout(resolve, ms));

// ── Long tasks (Chromium only: Firefox and WebKit have no 'longtask' entry type) ──────────────
const longTasksSupported =
  typeof PerformanceObserver !== 'undefined' && PerformanceObserver.supportedEntryTypes.includes('longtask');
const longTasks: PerformanceEntry[] = [];
if (longTasksSupported) {
  new PerformanceObserver((list) => {
    longTasks.push(...list.getEntries());
  }).observe({ type: 'longtask', buffered: true });
}

async function longTasksBetween(t0: number, t1: number): Promise<LongTaskStats | null> {
  if (!longTasksSupported) return null;
  await sleep(100); // entries are delivered asynchronously
  const inRange = longTasks.filter((e) => e.startTime >= t0 && e.startTime < t1);
  return {
    count: inRange.length,
    totalMs: inRange.reduce((sum, e) => sum + e.duration, 0),
    maxMs: inRange.reduce((max, e) => Math.max(max, e.duration), 0),
  };
}

// ── DOM helpers ─────────────────────────────────────────────────────────────────────────────
function viewport(): HTMLElement {
  const el = document.querySelector<HTMLElement>('.ogx__viewport');
  if (!el) throw new Error('grid viewport not found');
  return el;
}

function ariaRowCount(): number {
  return Number(viewport().getAttribute('aria-rowcount'));
}

function api(): GridApi<BenchRow> {
  if (!apiRef) throw new Error('grid not mounted');
  return apiRef.current;
}

function cellText(rowEl: Element | null, field: string): string {
  return rowEl?.querySelector(`[data-field="${field}"]`)?.textContent ?? '';
}

/**
 * Runs `start`, then resolves with t1 - t0 once the first frame showing the result (`ready()`) has
 * been painted. See the comment at the top of this file.
 */
async function timeToPaint(start: () => void, ready: () => boolean): Promise<{ ms: number; t0: number; t1: number }> {
  const t0 = performance.now();
  start();
  if (ready()) {
    await nextFrame(); // the frame that paints the commit
  } else {
    do {
      await nextFrame(); // a ready() here sees the DOM this frame is about to paint
      if (performance.now() - t0 > OP_TIMEOUT_MS) throw new Error('timed out waiting for the result on screen');
    } while (!ready());
  }
  await nextFrame(); // runs after that frame was painted
  const t1 = performance.now();
  return { ms: t1 - t0, t0, t1 };
}

/** Lets effects, ResizeObserver callbacks and follow-up renders finish before the next step. */
async function settle(frames = 10): Promise<void> {
  for (let i = 0; i < frames; i++) await nextFrame();
  await sleep(150);
}

async function op(start: () => void, ready: () => boolean, check: () => string | null): Promise<OpResult> {
  const { ms, t0, t1 } = await timeToPaint(start, ready);
  const longTaskStats = await longTasksBetween(t0, t1);
  const warning = check();
  await settle();
  return { ms, longTasks: longTaskStats, rowCount: ariaRowCount(), warning };
}

// ── The API driven by bench/run.mjs through page.evaluate ───────────────────────────────────
const bench: BenchApi = {
  generate(count, seed) {
    rows = generateRows(count, seed);
    return rows.length;
  },

  async refreshInterval() {
    // The display refresh interval (median rAF delta of 2 s of idle frames), and the share of idle
    // frames the scroll test's "over 16.7 ms" rule would count: the baseline noise of the engine.
    await nextFrame();
    const stamps: number[] = [];
    for (let i = 0; i < 121; i++) stamps.push(await nextFrame());
    const deltas = stamps.slice(1).map((t, i) => t - stamps[i]);
    const sorted = [...deltas].sort((a, b) => a - b);
    const intervalMs = sorted[Math.floor(sorted.length / 2)];
    return { intervalMs, idleOver16: deltas.filter((d) => d > intervalMs * 1.5).length / deltas.length };
  },

  async mount(height) {
    rowHeight = height;
    const container = document.getElementById('root');
    if (!container) throw new Error('#root missing');
    root = createRoot(container);
    const mountRoot = root;
    const { ms } = await timeToPaint(
      () => mountRoot.render(<BenchGrid rows={rows} rowHeight={rowHeight} onApiRef={(ref) => { apiRef = ref; }} />),
      () => document.querySelector('.ogx__row[data-rowindex]') !== null,
    );
    await settle();
    if (!apiRef) throw new Error('apiRef not bound after mount');
    return ms;
  },

  settle,

  async scroll(seed, intervalMs) {
    // 5 s of scripted scrolling, driven from requestAnimationFrame so the frame times are the
    // browser's own: 3 s at a constant 2,400 px/s (about 46 rows/s at 52 px), then 2 s of jumps to
    // a seeded random offset every 100 ms anywhere in the scrollable range. Each frame's time is the
    // difference between consecutive rAF timestamps.
    //
    // Headless browsers do not pace frames by a display's vsync: idle frames already vary between
    // about 16.6 and 18 ms (Chromium, Firefox) or 17 and 21 ms (WebKit), so a plain "> 16.7 ms" would
    // count most idle frames. A frame counts as over 16.7 ms when it took more than 1.5 refresh
    // intervals (25 ms at 60 Hz), so it missed at least one refresh, and as over 33 ms when it took
    // more than 2.5 intervals (41.7 ms), so it missed two or more.
    const el = viewport();
    el.scrollTop = 0;
    await settle(5);
    const maxTop = el.scrollHeight - el.clientHeight;
    let a = seed >>> 0;
    const rand = () => {
      a = (a + 0x6d2b79f5) >>> 0;
      let t = a;
      t = Math.imul(t ^ (t >>> 15), t | 1);
      t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
      return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
    };
    const deltas: number[] = [];
    let firstJumpFrame = -1;
    const CONSTANT_MS = 3000;
    const TOTAL_MS = 5000;
    const VELOCITY = 2.4; // px per ms
    const JUMP_EVERY_MS = 100;
    const start = await nextFrame();
    let prev = start;
    let nextJump = CONSTANT_MS;
    const t0 = performance.now();
    await new Promise<void>((resolve) => {
      const tick = (ts: number) => {
        deltas.push(ts - prev);
        prev = ts;
        const elapsed = ts - start;
        if (elapsed >= TOTAL_MS) {
          resolve();
          return;
        }
        if (elapsed >= CONSTANT_MS && firstJumpFrame === -1) firstJumpFrame = deltas.length;
        if (elapsed < CONSTANT_MS) {
          el.scrollTop = Math.min(maxTop, elapsed * VELOCITY);
        } else if (elapsed >= nextJump) {
          el.scrollTop = Math.floor(rand() * maxTop);
          nextJump += JUMP_EVERY_MS;
        }
        requestAnimationFrame(tick);
      };
      requestAnimationFrame(tick);
    });
    const t1 = performance.now();
    const longTaskStats = await longTasksBetween(t0, t1);
    const sorted = [...deltas].sort((x, y) => x - y);
    const pct = (p: number) => sorted[Math.min(sorted.length - 1, Math.floor((p / 100) * sorted.length))];
    const missed = (list: number[], factor: number) => list.filter((d) => d > intervalMs * factor).length / Math.max(1, list.length);
    const result: ScrollResult = {
      frames: deltas.length,
      p50: pct(50),
      p95: pct(95),
      p99: pct(99),
      over16: missed(deltas, 1.5),
      over33: missed(deltas, 2.5),
      over16Constant: missed(deltas.slice(0, firstJumpFrame), 1.5),
      over16Jumps: missed(deltas.slice(firstJumpFrame), 1.5),
      longTasks: longTaskStats,
      domRows: el.querySelectorAll('.ogx__row').length,
      domCells: el.querySelectorAll('[role="gridcell"]').length,
      domRowsAtRest: 0,
    };
    el.scrollTop = 0;
    await settle(30);
    result.domRowsAtRest = el.querySelectorAll('.ogx__row').length;
    return result;
  },

  async reach() {
    // Scroll to the very bottom and report the last row that is actually on screen. Browsers cap an
    // element's height, so with more rows than fit under the cap the last rows cannot be reached.
    const el = viewport();
    el.scrollTop = el.scrollHeight;
    await settle(20);
    el.scrollTop = el.scrollHeight; // again, in case the content grew after the first render
    await settle(20);
    const header = el.querySelector('.ogx__header, [role="rowgroup"]');
    const vp = el.getBoundingClientRect();
    const top = header ? header.getBoundingClientRect().bottom : vp.top;
    let lastIndex = -1;
    let lastEl: Element | null = null;
    for (const rowEl of el.querySelectorAll('.ogx__row[data-rowindex]')) {
      const r = rowEl.getBoundingClientRect();
      const index = Number(rowEl.getAttribute('data-rowindex'));
      if (r.bottom > top + 1 && r.top < vp.bottom - 1 && r.height > 0 && index > lastIndex) {
        lastIndex = index;
        lastEl = rowEl;
      }
    }
    const content = el.querySelector<HTMLElement>('.ogx__content');
    const result: ReachResult = {
      rowCount: rows.length,
      lastVisibleRow: lastIndex + 1,
      lastVisibleRowId: cellText(lastEl, 'id'),
      scrollHeight: el.scrollHeight,
      contentHeight: content ? content.getBoundingClientRect().height : 0,
      intendedHeight: rows.length * rowHeight,
      maxScrollTop: el.scrollHeight - el.clientHeight,
      scrollTop: el.scrollTop,
    };
    el.scrollTop = 0;
    await settle();
    return result;
  },

  async sortNumber() {
    let minIndex = 0;
    for (let i = 1; i < rows.length; i++) if (rows[i].amount < rows[minIndex].amount) minIndex = i;
    const header = () => document.querySelector('[role="columnheader"][data-field="amount"]');
    const result = await op(
      () => api().setSortModel([{ field: 'amount', sort: 'asc' }]),
      () => header()?.getAttribute('aria-sort') === 'ascending',
      () => {
        const first = cellText(viewport().querySelector('.ogx__row[data-rowindex="0"]'), 'id');
        return first === String(rows[minIndex].id) ? null : `sort amount: first row id ${first}, expected ${rows[minIndex].id}`;
      },
    );
    await op(() => api().setSortModel([]), () => header()?.getAttribute('aria-sort') !== 'ascending', () => null);
    return result;
  },

  async sortString() {
    const header = () => document.querySelector('[role="columnheader"][data-field="name"]');
    const result = await op(
      () => api().setSortModel([{ field: 'name', sort: 'asc' }]),
      () => header()?.getAttribute('aria-sort') === 'ascending',
      () => {
        const first = cellText(viewport().querySelector('.ogx__row[data-rowindex="0"]'), 'name');
        return first.startsWith('Ada Adams') ? null : `sort name: first row "${first}", expected "Ada Adams"`;
      },
    );
    await op(() => api().setSortModel([]), () => header()?.getAttribute('aria-sort') !== 'ascending', () => null);
    return result;
  },

  async filterString() {
    const term = 'nova';
    const expected = rows.reduce((n, r) => n + (r.name.toLowerCase().includes(term) ? 1 : 0), 0);
    return filterOp({ items: [{ field: 'name', operator: 'contains', value: term }] }, expected);
  },

  async filterNumber() {
    const expected = rows.reduce((n, r) => n + (r.amount > 5000 ? 1 : 0), 0);
    return filterOp({ items: [{ field: 'amount', operator: '>', value: 5000 }] }, expected);
  },

  async quickFilter() {
    // One term over all columns. The grid reads every cell's value and formatted text the first
    // time, so this is the cost of a first keystroke.
    return filterOp({ items: [], quickFilterValues: ['berg'] }, null);
  },

  async group() {
    const firstGroup = () => viewport().querySelector('.ogx__row--group');
    return op(
      () => {
        api().setAggregationModel({ amount: 'sum' });
        api().setRowGroupingModel(['region']);
      },
      () => cellText(firstGroup(), 'amount').trim() !== '',
      () => {
        const groups = viewport().querySelectorAll('.ogx__row--group').length;
        return groups === REGIONS.length ? null : `group: ${groups} group rows rendered, expected ${REGIONS.length}`;
      },
    );
  },

  unmount() {
    root?.unmount();
    root = null;
    apiRef = null;
    rows = [];
  },
};

async function filterOp(model: Parameters<GridApi['setFilterModel']>[0], expected: number | null): Promise<OpResult> {
  const before = ariaRowCount();
  const headerRows = before - rows.length;
  const result = await op(
    () => api().setFilterModel(model),
    () => ariaRowCount() !== before,
    () => {
      const shown = ariaRowCount() - headerRows;
      return expected === null || shown === expected ? null : `filter: ${shown} rows shown, expected ${expected}`;
    },
  );
  await op(() => api().setFilterModel({ items: [], quickFilterValues: [] }), () => ariaRowCount() === before, () => null);
  return { ...result, rowCount: result.rowCount - headerRows };
}

export function installBench(): void {
  window.__bench = bench;
}
